### ISSUE TITLE
Something went wrong. The following value was not able to initialize: canaryValue

### ISSUE THREAD

**Issue by photios** [ddurdle/OneDrive-for-KODI#7]
![canaryvalue](https://cloud.githubusercontent.com/assets/8793252/8295361/f6d97ddc-1911-11e5-98f3-b556142dd13f.png)
Problem occurs on two computers:
One runs Windows 7 SP1 and Kodi 14.2 and Onedrive 0.2.5
The other computer runs Windows 10 and Kodi 14.2 and Onedrive 0.2.5
Onedrive 0.2.5 in Kodi 14.2 worked fine on both computers until approximately June 15, 2015.
Since then, both computers have the same problem:
Clicking on Onedrive 0.2.5 to open it inside Kodi brings up a dialog box with the message:
"Something went wrong. The following value was not able to initialize: canaryValue"
(see attached screen dump)
Clicking OK in this dialog box shows the following inside the "Videos - onedrive" add-in:
[SEARCH]
<< Options>>
Any ideas how to get the "Onedrive" add-in to work again inside Kodi would be appreciated.

Possibilities: Given that Kodi and the Onedrive add-in are the same as those that worked earlier, and given that this problem occurs on two computers running two distinct versions of Windows, the most likely explanation is that this problem could be related to changes that Microsoft made to the Onedrive service itself.

**Comment by ddurdle** [comment]
Try the testing version in the testing repository - http://dmdsoftware.net/repository.ddurdle-testing/repository.ddurdle-testing.zip

or http://dmdsoftware.net/repository.ddurdle-testing/plugin.video.onedrive-testing-0.3.7.zip

Use OAUTH2.

**Comment by ddurdle** [comment]
Disabled ClientLogin mode.

**Comment by photios** [comment]
Hi,

The "onedrive testing" addin for Kodi works great. Thank you!

I have just one suggestion. Is it possible to see  and play videos that 
have been shared with me on OneDrive by other OneDrive users? I can see 
these shared ideo files under "Shared" in www.OneDrive.com and I can 
play them in a browser but the video player window inside a browser 
occupies less than 1/4 of the screen (very small) even when maximized. 
It is a horrible waste of screen space.

If you could make the "Shared" category of OneDrive appear in Kodi with 
your addin and play shared videos it would be ideal!

Thank you very much! Keep up the good work!

**Comment by ddurdle** [comment]
Shared content #9
